# Generated by Django 6.0 on 2025-12-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0004_alter_userprofile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
