# Generated by Django 6.0 on 2025-12-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0005_alter_userprofile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.CharField(choices=[('customer', 'customer'), ('business', 'business')], db_index=True, default='customer', max_length=10),
        ),
    ]
