# Generated by Django 6.0 on 2025-12-27 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0008_alter_offerdetail_delivery_time_in_days_and_more'),
        ('user_auth_app', '0004_alter_userprofile_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('business_user', 'reviewer')},
        ),
    ]
