# Generated by Django 6.0 on 2026-01-02 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0010_alter_review_options_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='revisions',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(-1)]),
        ),
    ]
